# Generated by Django 4.1.3 on 2022-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=500)),
                ('email', models.EmailField(default='', max_length=50)),
            ],
        ),
    ]
